name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        c: [
          {cc: gcc-9, cxx: g++-9, fc: gfortran-9},
          {cc: gcc-10, cxx: g++-10, fc: gfortran-10},
          {cc: gcc-11, cxx: g++-11, fc: gfortran-11},
          {cc: gcc-12, cxx: g++-12, fc: gfortran-12},
          {cc: gcc-13, cxx: g++-13, fc: gfortran-13},
          {cc: clang-13, cxx: clang++-13, fc: gfortran},
          {cc: clang-14, cxx: clang++-14, fc: gfortran},
          {cc: clang-15, cxx: clang++-15, fc: gfortran},
          ]

    env:
      CC: ${{ matrix.c.cc }}
      CXX: ${{ matrix.c.cxx }}
      FC: ${{ matrix.c.fc }}

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset default


  mac:
    runs-on: macos-latest

    strategy:
      matrix:
        c: [
          {cc: gcc-13, cxx: g++-13, fc: gfortran-13},
          {cc: clang, cxx: clang++, fc: gfortran-13}
          ]

    env:
      CC: ${{ matrix.c.cc }}
      CXX: ${{ matrix.c.cxx }}
      FC: ${{ matrix.c.fc }}

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset default

  windows:
    runs-on: windows-latest
    needs: linux
    timeout-minutes: 15

    env:
      CMAKE_GENERATOR: "MinGW Makefiles"

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - run: cmake --workflow --preset default
