name: ci_cmake

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cpp"
      - "**/*.c"
      - "**/CMakeLists.txt"
      - "**/*.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux-gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [7, 8, 9, 10, 11]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:
    - uses: actions/checkout@v2

    - name: install compilers
      run: |
        sudo apt update
        sudo apt install gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }} gfortran-${{ matrix.gcc-version }}

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V


  linux-clang:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        clang-version: ["6.0", 7, 8, 9, 10]

    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}
      FC: gfortran

    steps:
    - uses: actions/checkout@v3

    - name: install compilers
      run: |
        sudo apt update
        sudo apt install clang-${{ matrix.clang-version }}

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V

  mac:
    runs-on: macos-latest
    needs: linux-clang
    timeout-minutes: 5

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
    - uses: actions/checkout@v3

    - run: brew reinstall gcc

    - run: cmake -Bbuild
    - run: cmake --build build --parallel
    - run: ctest --test-dir build -V

  windows:
    runs-on: windows-latest
    needs: linux-gcc
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v3

    - run: cmake -B build -G "MinGW Makefiles"
    - run: cmake --build build --parallel
    - run: ctest --test-dir build -V
