name: ci_cmake

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cpp"
      - "**/*.c"
      - "**/CMakeLists.txt"
      - "**/*.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux-gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [7, 8, 9, 10, 11]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:
    - uses: actions/checkout@v2

    - name: install compilers
      run: |
        sudo apt update
        sudo apt install gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }} gfortran-${{ matrix.gcc-version }}

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V


  linux-clang:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        clang-version: ["6.0", 7, 8, 9, 10]

    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}
      FC: gfortran

    steps:
    - uses: actions/checkout@v2

    - name: install compilers
      run: |
        sudo apt update
        sudo apt install clang-${{ matrix.clang-version }}

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V

  mac:
    runs-on: macos-latest
    needs: linux-clang
    timeout-minutes: 5

    strategy:
      matrix:
        compiler: [ {cpp: g++-11, c: gcc-11}, {cpp: clang++, c: clang} ]

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}

    steps:
    - uses: actions/checkout@v2

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V

  windows:
    runs-on: windows-latest
    needs: linux-gcc
    timeout-minutes: 5

    env:
      CMAKE_GENERATOR: "MinGW Makefiles"

    steps:
    - uses: actions/checkout@v2

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V
