name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"


jobs:

  linux-gcc:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [9, 10, 11]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:
    - uses: actions/checkout@v3


    - run: cmake --workflow --preset default


  linux-clang:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    strategy:
      matrix:
        clang-version: [12, 13, 14]

    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}
      FC: gfortran

    steps:
    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default

  mac:
    runs-on: macos-latest
    needs: linux-clang
    timeout-minutes: 5

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default

  windows:
    runs-on: windows-latest
    needs: linux-gcc
    timeout-minutes: 15

    env:
      CMAKE_GENERATOR: "MinGW Makefiles"

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default
